# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 04:59
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180821_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='anonymous', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='lnglat',
            field=models.CharField(blank=True, help_text='위도/경도 포멧으로 입력하세요', max_length=50, validators=[blog.models.lnglat_validator]),
        ),
    ]
